# Generated by Django 3.2.23 on 2024-01-24 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='APK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_file', models.FileField(upload_to='apk_files/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apks', to='main.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
